import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedFirstnameWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedEnteryourmobilenumberWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedDateofbirthWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedMobilenumberWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedSacnyourNIDcardWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/Generated29458351Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedConfirmWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLastnameWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow1Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedPleaseconfirmyourcountrycodeandafteryourmobilenumberWid1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedWelcometoHCIEbankingWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLogInWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow3Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedCountryCodeWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow2Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/Generated880Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow3Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow5Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedArrow6Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax2widget/generated/GeneratedLine4Widget.dart';

/* Frame iPhone 11 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0625, 0.921875],
            colors: [
              Color.fromARGB(255, 0, 100, 251),
              Color.fromARGB(127, 0, 169, 207)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 11.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 240.0,
                child: GeneratedWelcometoHCIEbankingWidget1(),
              ),
              Positioned(
                left: 63.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 169.0,
                top: 826.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 42.0,
                child: GeneratedConfirmWidget(),
              ),
              Positioned(
                left: 325.0,
                top: 853.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow1Widget1(),
              ),
              Positioned(
                left: 324.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow2Widget1(),
              ),
              Positioned(
                left: 323.0,
                top: 853.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow3Widget1(),
              ),
              Positioned(
                left: 314.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 96.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 96.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 96.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 250.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 58.0,
                child: GeneratedSignUpWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 58.0,
                child: GeneratedLogInWidget1(),
              ),
              Positioned(
                left: 11.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 39.0,
                child: GeneratedEnteryourmobilenumberWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 58.0,
                child:
                    GeneratedPleaseconfirmyourcountrycodeandafteryourmobilenumberWid1(),
              ),
              Positioned(
                left: 16.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedCountryCodeWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 39.0,
                child: Generated880Widget1(),
              ),
              Positioned(
                left: 138.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 0.0,
                child: GeneratedArrow5Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 141.9980926513672,
                height: 3.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 185.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 223.00222778320312,
                height: 4.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 39.0,
                child: GeneratedMobilenumberWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 42.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 39.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 711.1275634765625,
                right: null,
                bottom: null,
                width: 367.0054626464844,
                height: 4.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 793.1275634765625,
                right: null,
                bottom: null,
                width: 367.0054626464844,
                height: 4.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 42.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 42.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 168.0029754638672,
                height: 4.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 168.0029754638672,
                height: 4.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 39.0,
                child: GeneratedFirstnameWidget(),
              ),
              Positioned(
                left: 218.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 39.0,
                child: GeneratedLastnameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 36.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 38.0,
                child: Generated29458351Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 42.0,
                child: GeneratedDateofbirthWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 39.0,
                child: GeneratedSacnyourNIDcardWidget(),
              ),
              Positioned(
                left: 325.0,
                top: 853.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow3Widget2(),
              )
            ]),
      ),
    ));
  }
}
