import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedFundTransferWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated1470tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedNazneenAfrozWidget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedTransID8J19MQKWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedAccountStatementWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated75315041Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedAvaiableBalanceinWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedSultanDineWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated7314511_preview1Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated350tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRestaurantWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedCashInWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated1500tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedTransactionsWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedTransID01750096Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/Generated221340tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedMobileRechargeWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedNavbarWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax4widget/generated/GeneratedPayBillWidget1.dart';

/* Frame iPhone 13 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.1145833358168602, 1.0],
                          colors: [
                            Color.fromARGB(255, 0, 101, 252),
                            Color.fromARGB(0, 0, 101, 252)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget4(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 80.0,
                              child: Generated7314511_preview1Widget3(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 41.0,
                              child: GeneratedNazneenAfrozWidget3(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 70.0,
                              child: Generated75315041Widget3(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 182.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 39.0,
                              child: GeneratedAvaiableBalanceinWidget(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 219.0,
                              right: null,
                              bottom: null,
                              width: 189.0,
                              height: 58.0,
                              child: Generated221340tkWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 180.0,
                              child: GeneratedRectangle32Widget(),
                            ),
                            Positioned(
                              left: 198.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 180.0,
                              child: GeneratedRectangle33Widget(),
                            ),
                            Positioned(
                              left: 361.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 180.0,
                              child: GeneratedRectangle34Widget(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 61.0,
                              child: GeneratedAccountStatementWidget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 350.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 58.0,
                              child: GeneratedFundTransferWidget(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 61.0,
                              child: GeneratedPayBillWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 501.0,
                              right: null,
                              bottom: null,
                              width: 239.0,
                              height: 61.0,
                              child: GeneratedTransactionsWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 570.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 76.0,
                              child: GeneratedRectangle35Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 76.0,
                              child: GeneratedRectangle36Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 768.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 76.0,
                              child: GeneratedRectangle37Widget(),
                            ),
                            Positioned(
                              left: 61.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 42.0,
                              child: GeneratedRestaurantWidget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 679.0,
                              right: null,
                              bottom: null,
                              width: 198.0,
                              height: 39.0,
                              child: GeneratedMobileRechargeWidget1(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 39.0,
                              child: GeneratedCashInWidget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 30.0,
                              child: GeneratedSultanDineWidget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 30.0,
                              child: GeneratedTransID8J19MQKWidget(),
                            ),
                            Positioned(
                              left: 66.0,
                              top: 806.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 30.0,
                              child: GeneratedTransID01750096Widget(),
                            ),
                            Positioned(
                              left: 286.0,
                              top: 594.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 30.0,
                              child: Generated1470tkWidget(),
                            ),
                            Positioned(
                              left: 291.0,
                              top: 693.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 30.0,
                              child: Generated350tkWidget(),
                            ),
                            Positioned(
                              left: 289.0,
                              top: 792.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 30.0,
                              child: Generated1500tkWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 867.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
