import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated\$15000Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated23452345Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedWalletWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated\$15000Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated13252555Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedPayUWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated245235Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated550000tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedMyCardsWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedCreditCardWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedBankAccountWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated\$23000Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedDBBLCardWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated96351576Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedDebitCardWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedNavbarWidget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax5widget/generated/Generated\$23000Widget1.dart';

/* Frame iPhone 13 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 873.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget3(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 233.0,
                              height: 76.0,
                              child: GeneratedMyCardsWidget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 104.0,
                              child: GeneratedRectangle39Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 104.0,
                              child: GeneratedRectangle41Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 620.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 104.0,
                              child: GeneratedRectangle42Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 761.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 104.0,
                              child: GeneratedRectangle43Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 338.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 104.0,
                              child: GeneratedRectangle40Widget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 39.0,
                              child: GeneratedCreditCardWidget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 131.0,
                              height: 39.0,
                              child: GeneratedDebitCardWidget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 494.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 39.0,
                              child: GeneratedDBBLCardWidget(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 42.0,
                              child: GeneratedWalletWidget(),
                            ),
                            Positioned(
                              left: 77.0,
                              top: 776.0,
                              right: null,
                              bottom: null,
                              width: 171.0,
                              height: 39.0,
                              child: GeneratedBankAccountWidget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 266.0,
                              right: null,
                              bottom: null,
                              width: 198.0,
                              height: 30.0,
                              child: Generated23452345Widget(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 401.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 30.0,
                              child: Generated13252555Widget(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 536.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 30.0,
                              child: Generated245235Widget(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 677.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 33.0,
                              child: GeneratedPayUWidget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 194.0,
                              height: 30.0,
                              child: Generated96351576Widget(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 42.0,
                              child: Generated$15000Widget(),
                            ),
                            Positioned(
                              left: 287.0,
                              top: 371.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 42.0,
                              child: Generated$23000Widget(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 513.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 39.0,
                              child: Generated550000tkWidget(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 655.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 42.0,
                              child: Generated$23000Widget1(),
                            ),
                            Positioned(
                              left: 296.0,
                              top: 794.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 42.0,
                              child: Generated$15000Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
