import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedSTWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedNavbarWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedArrow1Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedSendMoneyWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedNazneenAfrozWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedLogOutWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedPayBillWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedAvailableBalanceWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedMobileRechargeWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedAddmoneyWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/Generated75315041Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedPBWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedMRWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedAMWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedMPWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/Generated3589tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedStatementsWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedSMWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/Generated7314511_preview1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedCOWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedPngtreesettingicondesignvectorpngimage_16079041Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedMakePaymentWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedCashOutWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax1widget/generated/GeneratedEllipse2Widget3.dart';

/* Frame iPhone 13 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.1145833358168602, 1.0],
                          colors: [
                            Color.fromARGB(255, 0, 101, 252),
                            Color.fromARGB(0, 0, 101, 252)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: -2.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 440.0,
                              height: 924.0,
                              child: GeneratedRectangle2Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 254.0,
                              child: GeneratedRectangle1Widget3(),
                            ),
                            Positioned(
                              left: -11.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 172.0,
                              height: 179.0,
                              child: GeneratedEllipse1Widget3(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 132.0,
                              child: GeneratedEllipse2Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 246.0,
                              child: GeneratedRectangle3Widget1(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 180.0,
                              child: GeneratedEllipse3Widget(),
                            ),
                            Positioned(
                              left: -21.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 449.0,
                              height: 99.0,
                              child: GeneratedRectangle4Widget4(),
                            ),
                            Positioned(
                              left: 390.0,
                              top: 295.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 196.0,
                              child: GeneratedRectangle5Widget1(),
                            ),
                            Positioned(
                              left: 137.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 30.0,
                              child: GeneratedAvailableBalanceWidget(),
                            ),
                            Positioned(
                              left: 333.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 60.0,
                              child:
                                  GeneratedPngtreesettingicondesignvectorpngimage_16079041Widget(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 269.0,
                              height: 114.0,
                              child: Generated3589tkWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 49.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 138.0,
                              child: Generated7314511_preview1Widget(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 41.0,
                              child: GeneratedNazneenAfrozWidget(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 70.0,
                              child: Generated75315041Widget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 417.55712890625,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 41.0,
                              child: GeneratedSendMoneyWidget(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedMobileRechargeWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedCashOutWidget(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 579.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedMakePaymentWidget(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedPayBillWidget(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 688.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedAddmoneyWidget(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 749.0,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 44.0,
                              child: GeneratedStatementsWidget(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 821.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 41.0,
                              child: GeneratedLogOutWidget(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 80.0062484741211,
                              height: 0.0,
                              child: GeneratedArrow1Widget3(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle14Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle16Widget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 42.0,
                              child: GeneratedMRWidget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle17Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 575.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle15Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 631.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle18Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 682.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle19Widget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 687.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 42.0,
                              child: GeneratedAMWidget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 45.0,
                              child: GeneratedRectangle20Widget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 744.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 42.0,
                              child: GeneratedSTWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 42.0,
                              child: GeneratedPBWidget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 582.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 42.0,
                              child: GeneratedMPWidget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 42.0,
                              child: GeneratedCOWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 42.0,
                              child: GeneratedSMWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 871.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
