import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/GeneratedNavbarWidget5.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/GeneratedMdAhanafThamid18367941DBBLWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/GeneratedScreenshot202110280334581Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/Generated248302764_265272462203776_538669820627583101_n2Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax8widget/generated/Generated25000TkWidget.dart';

/* Frame iPhone 13 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 974.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -38.0,
                              top: -103.0,
                              right: null,
                              bottom: null,
                              width: 504.0,
                              height: 1077.0,
                              child: GeneratedScreenshot202110280334581Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget5(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 265.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 69.0,
                              child: GeneratedRectangle44Widget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 76.0,
                              child: Generated25000TkWidget(),
                            ),
                            Positioned(
                              left: 147.0,
                              top: 496.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 140.0,
                              child:
                                  Generated248302764_265272462203776_538669820627583101_n2Widget(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 636.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 88.0,
                              child: GeneratedRectangle45Widget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 652.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 58.0,
                              child:
                                  GeneratedMdAhanafThamid18367941DBBLWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
