import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedWelcometoHCIEbankingWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedSignUpWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedArrow1Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine11Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLogInWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedArrow2Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedArrow3Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedConfirmWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedNationalIDsmall1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax3widget/generated/GeneratedRectangle4Widget3.dart';

/* Frame iPhone 11 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0625, 0.921875],
            colors: [
              Color.fromARGB(255, 0, 100, 251),
              Color.fromARGB(127, 0, 169, 207)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 11.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 240.0,
                child: GeneratedWelcometoHCIEbankingWidget2(),
              ),
              Positioned(
                left: 63.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 169.0,
                top: 826.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 42.0,
                child: GeneratedConfirmWidget1(),
              ),
              Positioned(
                left: 325.0,
                top: 853.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow1Widget2(),
              ),
              Positioned(
                left: 324.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow2Widget2(),
              ),
              Positioned(
                left: 323.0,
                top: 853.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 0.0,
                child: GeneratedArrow3Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 96.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 96.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 218.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 96.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 250.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 58.0,
                child: GeneratedSignUpWidget2(),
              ),
              Positioned(
                left: 38.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 58.0,
                child: GeneratedLogInWidget2(),
              ),
              Positioned(
                left: 13.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 387.0,
                height: 301.0,
                child: GeneratedNationalIDsmall1Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 104.01922607421875,
                height: 5.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 400.0194091796875,
                top: 562.0,
                right: null,
                bottom: null,
                width: 104.01922607421875,
                height: 5.0,
                child: GeneratedLine11Widget(),
              ),
              Positioned(
                left: 401.0194091796875,
                top: 365.0,
                right: null,
                bottom: null,
                width: 104.01922607421875,
                height: 5.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 12.0194091796875,
                top: 562.0,
                right: null,
                bottom: null,
                width: 104.01922607421875,
                height: 5.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 128.06248474121094,
                height: 5.0,
                child: GeneratedLine14Widget(),
              ),
              Positioned(
                left: 273.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 128.06248474121094,
                height: 5.0,
                child: GeneratedLine15Widget(),
              ),
              Positioned(
                left: 273.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 128.06248474121094,
                height: 5.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 128.06248474121094,
                height: 5.0,
                child: GeneratedLine17Widget(),
              )
            ]),
      ),
    ));
  }
}
