import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedMedulHossainMasumWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedNazneenAfrozWidget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated250931881_573304327290432_5424857350562936685_n1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedEllipse7Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedNazneenAfroz18362441Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated17357923Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated250257658_584971456106885_4595463564677226531_n1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated75315041Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedMdAhanafThamid18367941Shimulmallick18372121Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated248302764_265272462203776_538669820627583101_n1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/Generated7314511_preview1Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax3widget/generated/GeneratedRectangle29Widget.dart';

/* Frame iPhone 13 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.1145833358168602, 1.0],
                          colors: [
                            Color.fromARGB(255, 0, 101, 252),
                            Color.fromARGB(0, 0, 101, 252)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 138.0,
                              child: Generated7314511_preview1Widget2(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 41.0,
                              child: GeneratedNazneenAfrozWidget2(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 70.0,
                              child: Generated75315041Widget2(),
                            ),
                            Positioned(
                              left: 274.17047119140625,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 280.0,
                              child: GeneratedPolygon1Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 207.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 484.0,
                              child: GeneratedEllipse6Widget(),
                            ),
                            Positioned(
                              left: 9.0,
                              top: 189.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 670.0,
                              child: GeneratedRectangle27Widget(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 42.0,
                              child: Generated17357923Widget(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 500.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 39.0,
                              child: GeneratedMedulHossainMasumWidget(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 233.0,
                              height: 98.0,
                              child: GeneratedNazneenAfroz18362441Widget(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 187.0,
                              child:
                                  GeneratedMdAhanafThamid18367941Shimulmallick18372121Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child: GeneratedRectangle28Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 379.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child: GeneratedRectangle29Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child: GeneratedRectangle30Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child: GeneratedRectangle31Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child:
                                  Generated248302764_265272462203776_538669820627583101_n1Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 595.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 104.0,
                              child:
                                  Generated250257658_584971456106885_4595463564677226531_n1Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 96.0,
                              child:
                                  Generated250931881_573304327290432_5424857350562936685_n1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.10998781150746569;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        47.07478332519531;

                                double percentHeight = 0.05723542116630669;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        53.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.4439252336448598,
                                      translateY: constraints.maxHeight *
                                          0.9427645788336934,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedEllipse7Widget2())
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
