import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedSendMoneyWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/Generated250931882Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedArrow7Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedSavingsWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/Generated18362441DBBLWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedNazneenAfrozWidget4.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedNavbarWidget4.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedBalance70000tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedProceedWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/Generated25000tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax7widget/generated/GeneratedScreenshot202110280334381Widget.dart';

/* Frame iPhone 13 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 854.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget4(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 39.0,
                              child: GeneratedSendMoneyWidget1(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 101.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 43.0,
                              child: GeneratedRectangle46Widget(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 107.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 42.0,
                              child: GeneratedSavingsWidget(),
                            ),
                            Positioned(
                              left: 377.0,
                              top: 131.0,
                              right: null,
                              bottom: null,
                              width: 2.0,
                              height: 0.0,
                              child: GeneratedArrow7Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 179.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 149.0,
                              child: GeneratedRectangle47Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 216.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 75.0,
                              child: Generated250931882Widget(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 216.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 41.0,
                              child: GeneratedNazneenAfrozWidget4(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 30.0,
                              child: Generated18362441DBBLWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 450.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 315.0,
                              child: GeneratedScreenshot202110280334381Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 784.0,
                              right: null,
                              bottom: null,
                              width: 329.0,
                              height: 50.0,
                              child: GeneratedRectangle48Widget(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 97.0,
                              height: 42.0,
                              child: GeneratedProceedWidget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 58.0,
                              child: Generated25000tkWidget(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 422.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 30.0,
                              child: GeneratedBalance70000tkWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
