import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedArrow2Widget3.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedBalanceWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated7314511_preview1Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedExpensesWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated75315041Widget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedNovemberWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedFoodPandaWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated3589tkWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated4590tkWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedIncomeWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedNavbarWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated3545Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedPandaMartWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedNazneenAfrozWidget1.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/Generated6676Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone13promax2widget/generated/GeneratedHCIMedicalCareWidget.dart';

/* Frame iPhone 13 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.1145833358168602, 1.0],
                          colors: [
                            Color.fromARGB(255, 0, 101, 252),
                            Color.fromARGB(0, 0, 101, 252)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 138.0,
                              child: Generated7314511_preview1Widget1(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 41.0,
                              child: GeneratedNazneenAfrozWidget1(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 70.0,
                              child: Generated75315041Widget1(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 235.0,
                              child: GeneratedEllipse4Widget(),
                            ),
                            Positioned(
                              left: 124.0,
                              top: 350.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 188.0,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 181.0,
                              top: 387.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 33.0,
                              child: GeneratedBalanceWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 47.0,
                              child: GeneratedRectangle21Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 251.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 42.0,
                              child: GeneratedNovemberWidget(),
                            ),
                            Positioned(
                              left: 171.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 9.0,
                              height: 0.0,
                              child: GeneratedArrow2Widget3(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 58.0,
                              child: Generated3589tkWidget1(),
                            ),
                            Positioned(
                              left: 181.0,
                              top: 579.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 50.0,
                              child: GeneratedRectangle23Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 579.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 50.0,
                              child: GeneratedRectangle22Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 42.0,
                              child: GeneratedExpensesWidget(),
                            ),
                            Positioned(
                              left: 225.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 42.0,
                              child: GeneratedIncomeWidget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 178.0,
                              child: GeneratedRectangle24Widget(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 178.0,
                              child: GeneratedRectangle25Widget(),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 58.0,
                              child: GeneratedHCIMedicalCareWidget(),
                            ),
                            Positioned(
                              left: 295.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 178.0,
                              child: GeneratedRectangle26Widget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 704.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 30.0,
                              child: GeneratedPandaMartWidget(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 30.0,
                              child: GeneratedFoodPandaWidget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 783.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 30.0,
                              child: Generated4590tkWidget(),
                            ),
                            Positioned(
                              left: 189.0,
                              top: 783.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 33.0,
                              child: Generated3545Widget(),
                            ),
                            Positioned(
                              left: 330.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 33.0,
                              child: Generated6676Widget(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 869.0,
                              right: null,
                              bottom: null,
                              width: 438.0,
                              height: 53.0,
                              child: GeneratedNavbarWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
