import 'package:flutter/material.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/Generated880Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedLogInWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedEnteryourmobilenumberWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedArrow4Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedPleaseconfirmyourcountrycodeandafteryourmobilenumberWid.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedMobilenumberWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedWelcometoHCIEbankingWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedCountryCodeWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedUnionWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedLetsGoWidget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/e_20bankapp/generatediphone11promax1widget/generated/GeneratedRectangle1Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0625, 0.921875],
            colors: [
              Color.fromARGB(255, 0, 100, 251),
              Color.fromARGB(127, 0, 169, 207)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 11.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 240.0,
                child: GeneratedWelcometoHCIEbankingWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 26.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 169.0,
                top: 826.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 39.0,
                child: GeneratedLetsGoWidget(),
              ),
              Positioned(
                left: 324.0,
                top: 840.9540405273438,
                right: null,
                bottom: null,
                width: 69.50000762939453,
                height: 23.091888427734375,
                child: GeneratedUnionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 96.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 96.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 96.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 58.0,
                child: GeneratedLogInWidget(),
              ),
              Positioned(
                left: 239.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 58.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 39.0,
                child: GeneratedEnteryourmobilenumberWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 58.0,
                child:
                    GeneratedPleaseconfirmyourcountrycodeandafteryourmobilenumberWid(),
              ),
              Positioned(
                left: 18.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedCountryCodeWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 39.0,
                child: Generated880Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 0.0,
                child: GeneratedArrow4Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 141.9980926513672,
                height: 3.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 223.00222778320312,
                height: 4.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 181.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 39.0,
                child: GeneratedMobilenumberWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 42.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 656.1275634765625,
                right: null,
                bottom: null,
                width: 367.0054626464844,
                height: 4.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 42.0,
                child: GeneratedWidget(),
              )
            ]),
      ),
    ));
  }
}
